config/routes.rb
Sblvacancy::Application.routes.draw do
  resources :microposts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help', via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, 'About Us') %>
<h1>About Us</h1>
<p>
  Our company provides services for automatization business process.<br>
  One of the main activities is the development of specific solutions for <a href='http://www.oracle.com/us/products/applications/siebel/overview/index.html'>Siebel CRM system</a>, the expansion of its standard functionality as separate modules. Our products help your business becomes successful.
  In our work we use only modern technology and programming languages​​.
</p>

<h2>About our products</h2>
<p>
Product modularity allows your company to save money and time, this is achieved by the fact that you do not need to hire highly paid developers to implement the functionality that has been developed by us. All you need - this is only module configuration and use.
</p>

<p>If you did not find the desired product in the <%= link_to "list of our products",   microposts_path %>, you can order its development. We are ready to undertake the development of any complexity.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Contact</h1>
If you are interested in some our product and want to get it, please contact us.<br>
<p>
  Email: <%= mail_to "bizlogiccompany@gmail.com" %>
</p>
<!--<p>
  Skype: dovnard
</p>-->

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Help</h1>
<p></p>
<p>If you are interested in some our product and want to get it, please contact us. <%= link_to "Our contacts",   contact_path %></p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>

<div class="center hero-unit">
  <%= image_tag("logo.png", alt: "Oracle Siebel CRM") %>
  <h1>BizLogic Systems</h1>

  <!--<h2>
    Сайт вакансий по 
    <a href="http://railstutorial.org/">Siebel CRM</a>
    системе.
  </h2>-->
  <!-- link_to "Sign up now!", signup_path, class: "btn btn-large btn-primary"-->
</div>

<table>
	<tr>
		<td align="center">
			<%= link_to image_tag("Siebel_logo.jpg", alt: "Oracle Siebel CRM"), 'http://www.oracle.com/us/products/applications/siebel/overview/index.html' %>
		</td>
		<td>
			Development of modular solutions for Sibel CRM system.
			<ul>
				<li>Integration Solutions</li>
				<li>Improve the existing functionality</li>
				<li>Solutions for business and customer interaction</li>
			</ul>
		</td>
	</tr>
	<tr>
		<td align="center">
			<%= link_to image_tag("javalogo.png", alt: "Java"), 'http://www.oracle.com/us/technologies/java/overview/index.html' %>
		</td>
		<td>
			Developing with Java.
			<ul>
				<li>Creating customized solutions for small businesses and enterprise companies</li>
				<li>Enterprise service bus</li>
				<li>Desktop applications</li>
				<li>Web applications</li>
				<li>Integrations with Oracle Siebel CRM and other systems</li>
			</ul>
		</td>
	</tr>
</table>