config/routes.rb
Sblvacancy::Application.routes.draw do
  resources :microposts

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  root to: 'static_pages#home'
  
  match '/signup',  to: 'users#new', via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'

  match '/help',    to: 'static_pages#help', via: 'get'
  match '/about',   to: 'static_pages#about', via: 'get'
  match '/contact', to: 'static_pages#contact', via: 'get'

end

app/models/micropost.rb
class Micropost < ActiveRecord::Base
	belongs_to :user
	validates :content, length: { maximum: 140, minimum: 10 }
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_action :set_micropost, only: [:show, :edit, :update, :destroy]

  # GET /microposts
  # GET /microposts.json
  def index
    @microposts = Micropost.all
  end

  # GET /microposts/1
  # GET /microposts/1.json
  def show
  end

  # GET /microposts/new
  def new
    @micropost = Micropost.new
  end

  # GET /microposts/1/edit
  def edit
  end

  # POST /microposts
  # POST /microposts.json
  def create
    @micropost = Micropost.new(micropost_params)

    respond_to do |format|
      if @micropost.save
        format.html { redirect_to @micropost, notice: 'Micropost was successfully created.' }
        format.json { render action: 'show', status: :created, location: @micropost }
      else
        format.html { render action: 'new' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /microposts/1
  # PATCH/PUT /microposts/1.json
  def update
    respond_to do |format|
      if @micropost.update(micropost_params)
        format.html { redirect_to @micropost, notice: 'Micropost was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @micropost.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /microposts/1
  # DELETE /microposts/1.json
  def destroy
    @micropost.destroy
    respond_to do |format|
      format.html { redirect_to microposts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_micropost
      @micropost = Micropost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def micropost_params
      params.require(:micropost).permit(:content, :shortdesc, :description, :user_id)
    end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for(@micropost) do |f| %>
  <% if @micropost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
      <% @micropost.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_field :content %>
  </div>
  <div class="field">
    <%= f.label :shortdesc %><br>
    <%= f.text_area :shortdesc %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/microposts/edit.html.erb
<h1>Editing micropost</h1>

<%= render 'form' %>

<%= link_to 'Show', @micropost %> |
<%= link_to 'Back', microposts_path %>

app/views/microposts/index.html.erb
<h1>Products</h1>

<table width="100%">
  <thead>
    <tr>
      <th width="150px" style="border-bottom: 1px solid gray;">Product</th>
      <th  style="border-bottom: 1px solid gray;">Description</th>
      <th style="border-bottom: 1px solid gray;"></th>
<!--<% if (current_user.name == 'bizlogic') %>      -->
<th style="border-bottom: 1px solid gray;"></th>
      <th style="border-bottom: 1px solid gray;"></th>
<!--<% end %>-->
    </tr>
  </thead>

  <tbody>
    <% @microposts.each do |micropost| %>
      <tr>
        <td style="border-bottom: 1px solid lightgray;"><%= micropost.content %></td>
        <td style="border-bottom: 1px solid lightgray;"><%= micropost.shortdesc.html_safe %></td>
        <td style="border-bottom: 1px solid lightgray;"><%= link_to 'Show', micropost %></td>
<!--<% if (current_user.name == 'bizlogic') %>      -->
        <td style="border-bottom: 1px solid lightgray;"><%= link_to 'Edit', edit_micropost_path(micropost) %></td>
       	<td style="border-bottom: 1px solid lightgray;"><%= link_to 'Destroy', micropost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
<!--<% end %>-->
      </tr>
    <% end %>
  </tbody>
</table>

<% if (current_user.name == 'bizlogic') %>
	<%= link_to 'New Micropost', new_micropost_path %>
<% end %>

app/views/microposts/new.html.erb
<h1>New micropost</h1>

<%= render 'form' %>

<%= link_to 'Back', microposts_path %>

app/views/microposts/show.html.erb
<p id="notice"><%= notice %></p>

<h1><%= @micropost.content %></h1>
<p>
  <strong>Short Description:</strong>
  <%= @micropost.shortdesc.html_safe %>
</p>

<p>
  <strong>Description:</strong>
  <p><%= @micropost.description.html_safe %></p>
</p>

<!--<p>
  <strong>User:</strong>
  %= @micropost.user_id %
</p>-->

<%= link_to 'Edit', edit_micropost_path(@micropost) %> |
<%= link_to 'Back', microposts_path %>